### ISSUE TITLE
option for outputting warnings only

### ISSUE THREAD

**Issue by markusfalk** [yargalot/grunt-accessibility#18]
maybe it is useful to have an option that let users decide what they want to be in their report. In short: I would like only warnings to show up

thanks again :)

**Comment by markusfalk** [comment]
Thanks for the great effort!! 

But what I meant with the issue is not weather to generate a report in the target folder or not. 
Rather I would like to suggest an option that lets me decide what I want to be shown as output.

Maybe something like this:

```javascript
options: {
  verboseTypes: [
    "notice": false,
    "warning": true,
    "error": true
  ]
}
```

This way I only get warnings and errors.

**Comment by yargalot** [comment]
Ah right, I'll have a look into it then. Should be easy.
