### ISSUE TITLE
Fatal error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by foxreymann** [yargalot/grunt-accessibility#22]
Steven,

I've just added your plugin to my project and I can't run any test as every time I get an error:

    $ grunt accessibility
    Running "accessibility:test" (accessibility) task
    Running accessibility tests
    Page Loaded. Starting Tests
    Fatal error: Maximum call stack size exceeded

My configuration:

		accessibility: {
			options : {
				accessibilityLevel: 'WCAG2AA'
			},
			test : {
				files: [{
					expand  : true,
					force: true,
					src     : ['build/no-template.html'],
					dest    : '',
					ext     : '-report.txt'
				}]
			}
		},

**Comment by thedigitalman** [comment]
I am having this issue with the 2.0 release as well.

```javascript
accessibility: {
	options: {
		accessibilityLevel: 'WCAG2AA',
		outputFormat: 'txt',
		domElement: true,
		force: true
	},
	test: [{
		expand: true,
		src: ['index.html'],
		dest: 'TestResults/',
		ext: '-wcga2aa-report'
	}]
},
```

**Comment by XhmikosR** [comment]
Does this still happen?

**Comment by yargalot** [comment]
@XhmikosR Never been able to replicate it tbh 😓

**Comment by yargalot** [comment]
This has been fixed with the Maxbuffer https://github.com/yargalot/AccessSniff/commit/e6fbba6bf09f343646e5b9bdf76280500280413b commit in v2.4.1
