### ISSUE TITLE
Option for outputting specific types of feedback

### ISSUE THREAD

**Issue by yargalot** [yargalot/grunt-accessibility#23]
As per feedback in #18 
```
options: {
  verboseTypes: [
    "notice": false,
    "warning": true,
    "error": true
  ]
}
```

**Comment by gunnx** [comment]
+1

**Comment by SubZane** [comment]
+2

**Comment by yargalot** [comment]
Hey guys, Im currently converting this to a standalone library to use in this project. I'll throw it there then make it part of the coming release.

**Comment by markusfalk** [comment]
great

**Comment by yargalot** [comment]
https://github.com/yargalot/AccessSniff#report-levels, 3.0.0 has it now ;D
