### ISSUE TITLE
without 'dest:' option report is written to source html file

### ISSUE THREAD

**Issue by markusfalk** [yargalot/grunt-accessibility#24]
```javascript
accessibility: {
      options : {
        accessibilityLevel: 'WCAG2<%= WCAG2 %>',
        accessibilityrc: true,
        domElement: true
      },
      development : {
        files: [{
          expand  : true,
          cwd     : 'build/',
          src     : ['*.html'],
         // dest    : 'WCAG2-reports/',
         // ext     : '-report.txt'
        }]
      }
    },
```

when no 'dest:' option is given the report will be written into the tested html file deleting all HTML in it

**Comment by yargalot** [comment]
That doesnt sound good, must only be like that with the globbing pattern =/

**Comment by yargalot** [comment]
Hey Mate, I cant replicate this one, Might need some more info :(

**Comment by markusfalk** [comment]
What kind of info would help?

**Comment by yargalot** [comment]
Well, I couldnt get it to overwrite the actual html file, but i fixed the globbing pattern issue, so give the new version a shot and see if it still does it. Mightve fixed it.

**Comment by markusfalk** [comment]
works like charm for me now with 2.2.0 

thank you :)

**Comment by yargalot** [comment]
Awesome, Let me know if you think go anything else or there are any more issues. 

Btw you can use ```src: [*.html]``` now instead of ```files: {[]}```.
