### ISSUE TITLE
output to file overwrites previous file

### ISSUE THREAD

**Issue by Andykmcc** [yargalot/grunt-accessibility#25]
I have a build directory with multiple .html files in it. I am trying to audit each one and output the results of the audit to a file located in wcag2-reports/. After each run there are not any errors and the dest. directory only has one file in it. That file is always the last one audited from the src. directory. My grunt-accessibility config is below. 

```
module.exports = {
  options : {
    accessibilityLevel: 'WCAG2A',
    force: true,
    outputFormat: 'json',
    verbose: false
  },
  test : {
    files: [{
      expand  : true,
      cwd     : 'build/',
      src     : ['*.html'],
      dest    : 'wcag2-reports/',
      ext     : '-report'
    }]
  }
};
```

**Comment by yargalot** [comment]
Yep, will be having a look at the report gen stuff this weekend, seems I buggered something up in the latest release

**Comment by yargalot** [comment]
ref #24

**Comment by Andykmcc** [comment]
yeah, im planning on digging into it this weekend as well.

**Comment by yargalot** [comment]
Sweet, sounds like a plan. Will be good to get input!

**Comment by yargalot** [comment]
Hey Mate, Can you give this another shot. See what happens
