### ISSUE TITLE
Hang when using ** glob

### ISSUE THREAD

**Issue by JoshSchreuder** [yargalot/grunt-accessibility#26]
When using the ** glob operator in my files / src array, the task hangs indefinitely when processing the first file in that directory.

Config:
```js
files: [{
        expand: true,
        flatten: false,
        cwd: '<%= project.paths.forms %>',
        src: [ 'modules/**/*.html' ],
        dest: '<%= project.paths.reportData %>/WCAG'
    }]
```

It works for directories if I leave out the globbing pattern, so I think it is related to that.

v1.2.1 is the last version that didn't hang, but it also only processes the first file matched in the globbing pattern for some reason.

**Comment by yargalot** [comment]
Hey Mate, Quick question. Are you using 2.1.1?

Just tried it then and it seems to be working, Had to do some fixes for globbing in the 2.1.1 branch where is was broken

![screenshot 2015-03-02 14 29 26](https://cloud.githubusercontent.com/assets/790013/6435022/bc43e18e-c0e8-11e4-9ed2-8b1c48788743.png)

**Comment by JoshSchreuder** [comment]
@yargalot yeah I tried originally on 2.1.1 and then tried all version back from there and v1.2.1 was the last one that didn't hang.

I can try and give you some more verbose information if you like.

**Comment by yargalot** [comment]
Yeh if you could that would be great. Ill try and replicate the folder structure you have and go from there.

**Comment by JoshSchreuder** [comment]
Not sure if there's any way to get any more information out, maybe I can throw some logging statements in somewhere if you give me some relevant line numbers?

Running 2.1.1:

Console output:
```
λ grunt accessibility
Running "accessibility:frontend_index" (accessibility) task
Testing ../Source/www/Forms/index.html

Report Finished
File "ReportData/WCAG/index.html.json" created.

Running "accessibility:frontend_partials" (accessibility) task
Testing ../Source/www/Forms/modules/ApplicationEditor/ApplicationEditor.html
```

Config:
```js
config.accessibility.frontend_index = {
    options: {
        accessibilityLevel: 'WCAG2A',
        force: true,
        domElement: true,
        outputFormat: 'json',
        verbose: false,
        ignore: [
            // Justification: The title element is set via Angular binding
            'WCAG2A.Principle2.Guideline2_4.2_4_2.H25.2'
        ]
    },
    files: [{
        expand: true,
        flatten: false,
        cwd: '<%= project.paths.forms %>',
        src: [ 'index.html' ],
        dest: '<%= project.paths.reportData %>/WCAG'
    }]
};
config.accessibility.frontend_partials = {
    options: {
        accessibilityLevel: 'WCAG2A',
        force: true,
        domElement: true,
        outputFormat: 'json',
        verbose: false,
        ignore: [
            // Justification: HTML, HEAD, BODY tags not required in partials
            'WCAG2A.Principle2.Guideline2_4.2_4_2.H25.1.NoTitleEl',
            // Justification: HTML, HEAD, BODY tags not required in partials
            'WCAG2A.Principle3.Guideline3_1.3_1_1.H57.2'
        ]
    },
    files: [{
        expand: true,
        flatten: false,
        cwd: '<%= project.paths.forms %>',
        src: [ 'modules/**/*.html' ],
        dest: '<%= project.paths.reportData %>/WCAG'
    }]
}
```

**Comment by yargalot** [comment]
Just as a quick question, what happens if you use the globbing pattern on on the index.html file? Does it hang as well? Wondering if the testing process is hanging on the partials.

**Comment by JoshSchreuder** [comment]
> Just as a quick question, what happens if you use the globbing pattern on on the index.html file? Does it hang as well? Wondering if the testing process is hanging on the partials.

Good thinking. It works with the globbing in the index.html task. I guess it is a partial issue then. Though I have had this task working before in the past with partials...

**Comment by yargalot** [comment]
I knocked off the doctype on a file, Seems to hang on if the doctype doesnt exist, which means bad for partials.

I'll knock up a fix

**Comment by yargalot** [comment]
I updated the version of HTML_Codesniffer, so it might be to do with that.

**Comment by yargalot** [comment]
Wait no, its the way it picks up the html of the file and inserts the line numbers. Will fix that one.

**Comment by JoshSchreuder** [comment]
@yargalot thanks for looking into it mate, I appreciate it.

**Comment by yargalot** [comment]
Hey mate,

Can you try out the new version? See if it still happens? Released 2.2.0 then :)

**Comment by JoshSchreuder** [comment]
@yargalot - works perfectly now, many thanks for getting it fixed for me!

**Comment by yargalot** [comment]
@JoshSchreuder No probs, Let me know if there are any issues!
