### ISSUE TITLE
svg xlink:href causes error but should not

### ISSUE THREAD

**Issue by markusfalk** [yargalot/grunt-accessibility#30]
Example SVG:

``` svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g>
    <a xlink:href="#anchor">
      <text>Link</text>
    </a>
  </g>
</svg>
```

Links cause the following error
- WCAG2A.Principle4.Guideline4_1.4_1_2.H91.A.Placeholder

I would expect this to understand the namespace and find the href behind xlink.

Thank you :)

**Comment by prantlf** [comment]
This Grunt task integrates of [AccessSniff](https://github.com/yargalot/AccessSniff) to perform the validation. You can ask for improving the Grunt integration here.

If you want to fix or change the validation engine, you need to open an issue for [HTML_CodeSniffer](https://github.com/squizlabs/HTML_CodeSniffer), which used internally by `AccessSniff`.

**Comment by markusfalk** [comment]
closing - out of date
