### ISSUE TITLE
Make output less verbose

### ISSUE THREAD

**Issue by XhmikosR** [yargalot/grunt-accessibility#31]
Example:

```
Running "bootlint:files" (bootlint) task

>> 52 file(s) lint free.
```

Passing `--verbose` should show all the info, but by default, that info is just extra bloat.

I can have a look when I have some time, unless someone else beats me to it.

**Comment by XhmikosR** [comment]
@yargalot: pehaps this should be implemented in AccessSniff instead? It just too long now compared to other tools. See https://travis-ci.org/mpc-hc/mpc-hc.org/builds/110557334#L1012

**Comment by yargalot** [comment]
Ok new version should fix this, @XhmikosR can you reinstall it with the patch and se what it outputs?

**Comment by XhmikosR** [comment]
Now it is less verbose, indeed.

One minor change; I'd remove the newline before the success message and follow the same scheme all the grunt plugins use with `grunt.ok`.

I wonder if it's possible to speed the whole process by running one time AccessSniff.

**Comment by yargalot** [comment]
Yep makes sense, 

On the performance end, there are probably some easy wins there But im more thinking its the phantomjs bootup that takes the most time. Need to look more into it

**Comment by yargalot** [comment]
Whoops hit the wrong button and submitted the comment before its finished. But anyway, yeh lets move this to the accessSniff repo, will have to investigate more.

**Comment by XhmikosR** [comment]
@yargalot: this is valid again :/

**Comment by yargalot** [comment]
kk, looking now

**Comment by XhmikosR** [comment]
I'm thinking, this will be much easier to fix if performance was improved. At the moment, the best you can do is not show anything, which isn't good either since it takes a couple of minutes for the task to run.

**Comment by yargalot** [comment]
Ok, just pushed a new version of the grunt plugin to fix this, should be good to go. Tested it a local repo of the mpc site ;)

**Comment by yargalot** [comment]
The performance is pretty bad atm, Im thinking if we could open the phantomjs instance, leave it open and fee new sites to it that would be a lot better.

Only problem is Im unsure on how to do this atm, so need to look into it

**Comment by XhmikosR** [comment]
Almost there :P

```
Running "accessibility:test" (accessibility) task

52 files lint free!

File "/home/travis/build/mpc-hc/mpc-hc.org/reports/report.null" created. Report Finished
```

**Comment by yargalot** [comment]
Lol

**Comment by yargalot** [comment]
Ah the defaults from accessSniff merge with the options you pass in the grunt plugin. Ill change the defaults and release it. Two secs

**Comment by yargalot** [comment]
Ok thats fixed with the new release of AccessSniff @XhmikosR 😄

**Comment by XhmikosR** [comment]
I see, thanks!
