### ISSUE TITLE
Fix error report

### ISSUE THREAD

**Issue by XhmikosR** [yargalot/grunt-accessibility#36]
@yargalot: This was unintentionally broken in https://github.com/yargalot/grunt-accessibility/commit/548e9a89ad1d28b612efc7441aa8ad97ee926608, I just commented it out to get things to work first.

**Comment by yargalot** [comment]
Got it throwing catch now, so that will fix it up https://github.com/yargalot/AccessSniff/commit/f74e70d61fbff40d509fe1eea21f99363c4f3510

**Comment by XhmikosR** [comment]
Thanks!
